[package]
name = "nicked"
version = "0.1.0"
authors = ["Jack Kavanagh <jackkav@gmail.com>"]
edition = "2018"

[dependencies]
nickel = "0.11.0"

[dev-dependencies]
catflap = "1.1.0"
cargo-watch = "7.2.2"
